// Generated by LiveScript 1.3.1
var chromaJs, out$ = typeof exports != 'undefined' && exports || this;
chromaJs = require('chroma-js');
out$.flRgba = flRgba;
function flRgba(it){
  if (it.alpha == null) {
    it = chromaJs(it);
  }
  return (function(){
    switch (it.alpha()) {
    case 1:
      return it.hex();
    default:
      return it.hex('rgba');
    }
  }()).toUpperCase();
}