// Generated by LiveScript 1.3.1
var DOMObject;
module.exports = DOMObject = (function(){
  DOMObject.displayName = 'DOMObject';
  var prototype = DOMObject.prototype, constructor = DOMObject;
  prototype.toString = function(){
    return "[object " + this.constructor.name + "]";
  };
  function DOMObject(){}
  return DOMObject;
}());